### ISSUE TITLE
Extra quote is generated for version numbers in the .dot file

### ISSUE THREAD

**Issue by R0kshan** [diverse-project/pdedependencies2dot#2]
Sample project used to view dependencies : <https://git.eclipse.org/c/mmt/org.eclipse.atl.git/>

The generated `.dot` file contains an extra quote in all lines containing a version number. For example in line 19 of the generated `.dot` file : 
```
"3.1.0)""[fillcolor=lightgray];
```
This extra quote creates the following error when trying to convert the `.dot` to `.pdf` using the command `dot -Tpdf atl_deps.dot > atl_deps.pdf` :

```
Error: atl_deps.dot: syntax error in line 19 near '.'
```

**Comment by maoschanz** [comment]
the root of the problem is this line https://github.com/diverse-project/pdedependencies2dot/blob/c8f1f6eb003a69c179da7582b5fed2bb0427bcff/src/main/java/fr/inria/diverse/pdedependencies2dot/Pdedependencies2model.xtend#L184 because "," is also the delimiter between versions in situations like 

    org.antlr.runtime;bundle-version="[3.0.0,3.1.0)",

so here `3.1.0)"` is (wrongly) handled as the name of a dependency
